version: "3.8"
networks:
  app-tier:
    driver: bridge

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node
    container_name: nodejs_stack_container
    restart: always
    env_file: .env
    ports:
      - "7000:7000"

  db:
    image: mysql:8.0.28
    container_name: db_stack_container
    restart: always
    env_file: .env
    environment:
      MYSQL_USER: "bayata"
      MYSQL_DATABASE: "stackDB"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: "password"
    networks:
      - app-tier
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    expose:
      - "3306"
