version: "3.8"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node
    container_name: nodejs_stack_container
    restart: always
    env_file: .env

    ports:
      - "8000:8000"
    expose:
      - "8000"

  db:
    image: mysql:8.0.28
    container_name: db_stack_container
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: "stackDB"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3307:3307"
    security_opt:
      - seccomp:unconfined
    expose:
      - "3307"
